### ISSUE TITLE
Frida-compile - process is not defined

### ISSUE THREAD

**Issue by sushi2k** [federicodotta/Brida#105]
Hi, 

I have 2 Kali VM's (latest Kali), one on a 2019 MacBook (Intel) and one on a 2021 MacBook (ARM/M1).

On the Intel I can use Brida in Burp without issues and `frida-compile` works. 

When doing the same setup, with the same Burp and Brida version on the M1 MacBook and install the latest Frida-compile I get the following error in Brida when clicking on "Compile and Reload JS":

```
process is not defined
 Error during frida-compile, potentially caused by compilation errors. Aborting. If exception details are not returned, try to run frida-compile manually. frida-compile command:  "/home/mastg/.local/bin/frida-compile" -o "/home/mastg/brida/bridaGeneratedCompiledOutput.js" "/home/mastg/brida/brida.js"  
```

It's the default JS files, that have been created by pressing the button "Create default JS files". Any idea what the problem might be on ARM? 

![image](https://user-images.githubusercontent.com/5951320/216761042-2af9f79f-2b01-4ae0-bfb2-cc90b23c5633.png)

![Screenshot at Feb 04 18-00-05](https://user-images.githubusercontent.com/5951320/216761022-6971b453-9d3a-4547-96af-24d7dcc54f90.png)

**Comment by federicodotta** [comment]
Hi @sushi2k,

Sorry for the delay in the response. I was quite busy on other projects.

Your issue seems related to frida-compile. Unfortunately I don't have an ARM Mac to try at the moment. Maybe you can try to open an issue directly in the frida-compile project. 

Do you have the same issue also if you compile other JS files?

Federico
