### ISSUE TITLE
App spawned but error

### ISSUE THREAD

**Issue by zulfakar404** [federicodotta/Brida#106]
App spawned but got this error on console

java.util.concurrent.TimeoutException java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204) burp.BurpExtender.executePyroCall(BurpExtender.java:2826) burp.BurpExtender.spawnApplication(BurpExtender.java:2862) burp.BurpExtender.actionPerformed(BurpExtender.java:3007) java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) java.desktop/java.awt.Component.processMouseEvent(Component.java:6626) java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389) java.desktop/java.awt.Component.processEvent(Component.java:6391) java.desktop/java.awt.Container.processEvent(Container.java:2266) java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001) java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324) java.desktop/java.awt.Component.dispatchEvent(Component.java:4833) java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310) java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780) java.desktop/java.awt.Component.dispatchEvent(Component.java:4833) java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722) java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716) java.base/java.security.AccessController.doPrivileged(AccessController.java:399) java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746) java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744) java.base/java.security.AccessController.doPrivileged(AccessController.java:399) java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743) java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by federicodotta** [comment]
Hi @zulfakar404,

Sorry for the delay in the response. I was quite busy on other projects.

That particular exception is caused by some lines of code I introduced in Brida to stop communication with Frida when it does not receive a response within 30 seconds. The purpose is avoid to stuck Burp Suite if something goes wrong in the device.

If you received that error there is some issues with Frida hooks. You can try the following approaches: 

1. try to run Brida with the default code without adding any custom code and without enabling hooks from the GUI, in order to see if this way the application works correctly. If this is the case, probably there is a hook that cause issues or that intercept too much calls/print too much output and causes delays.
2. try to run Frida from the command line, in order to see if there are some general issues with Frida. If this is the case, you can try a different version of Frida.

Federico
