### ISSUE TITLE
there is an error when crypt response

### ISSUE THREAD

**Issue by ngocanh2822** [federicodotta/Brida#120]
mycrypt in request worked but response was error. I can run it on the Ubuntu virtual machine, but Windows has an error.
![image](https://github.com/federicodotta/Brida/assets/59717302/8b6e6248-4160-4ba1-9437-8e173b6d9b82)
![image](https://github.com/federicodotta/Brida/assets/59717302/375b62c0-67e3-4991-b520-b428e7c15e46)
please help me

**Comment by federicodotta** [comment]
Hi @ngocanh2822,

Unfortunately, I don't have many information to help you. I suspect an error in your JS functions (maybe a difference between requests and responses in the mobile code) because Brida environment seems to work well (the requests has been correctly decrypted). 

The exception said that the replaceAll function has been executed on a null object. Probably there is some issue in the source of that object that returned a null value.

Federico
