### ISSUE TITLE
Parameter cannot be passed

### ISSUE THREAD

**Issue by CHINA-china** [federicodotta/Brida#123]
I tried writing an rpc function and found that I couldn't pass in parameter values
![image](https://github.com/federicodotta/Brida/assets/92798047/78e3e1e8-b951-44d2-8870-1a421343e33a)
![image](https://github.com/federicodotta/Brida/assets/92798047/0b2a0e4d-4111-4e36-ab8b-df7bd2d835ea)
The following is the environment I am using
```
Brida-0.6-pre
Python 3.7.0
Frida 14.2.18
frida-compile.cmd 10.2
```
![image](https://github.com/federicodotta/Brida/assets/92798047/83036028-1b39-4f04-a29a-7c96a0e02d49)
![image](https://github.com/federicodotta/Brida/assets/92798047/182335d7-0c15-461d-a6ed-e91bfa1724cd)
![image](https://github.com/federicodotta/Brida/assets/92798047/7db94eab-f437-46a1-85ff-a957c740add1)

**Comment by federicodotta** [comment]
Hi @CHINA-china,

Unfortunately, I cannot replicate your issue. I tried with many different environments and configurations but parameters work correctly.

Only one thing. If you maybe clicked on the "Add parameter" button before inserting the string, for a graphical issue with Java it is possible that you have an empty parameter very difficult to see because very slim. This can cause your issue. In this case, you have to select the empty parameter and remove it. The following picture that describes better what I wrote.

![image](https://github.com/federicodotta/Brida/assets/1651767/3a2f2915-9c73-411f-986d-ac928d295694)
