### ISSUE TITLE
Failed Get Result Custom Plugin

### ISSUE THREAD

**Issue by yayip** [federicodotta/Brida#128]
Hi, 

I run custom plugin to call function AES encryption and decryption, but always got java error like this and in the Brida not show anyting. 

![image](https://github.com/federicodotta/Brida/assets/39186995/1243b362-571b-4570-81b1-06c3c82e1d31)

And configuration my custom plugin like this :

![image](https://github.com/federicodotta/Brida/assets/39186995/c4bdee46-e111-415f-a0f9-a113e726964f)

And my script to call function like this : 

![image](https://github.com/federicodotta/Brida/assets/39186995/731eedad-9053-438c-9d8f-4af3444617ff)

Thanks.

**Comment by federicodotta** [comment]
Hi @yayip,

That exception is caused by the fact that for some reason the return value of your function is null. Probably your JavaScript function is not working properly for some reason.

You can try the function in the "Debug export" pane or even better directly in the Frida CLI, in order to check that the function is working properly. 

One potential issue: "nf.a.a" and "nf.a.b" are static functions? Because if not, you have to first get an instance of an object of type "nf.a". You can do that in many different ways like saving a reference of the object you need with a Frida hook, instantiate the object by yourself or use Java.choose to search for the object in the Java heap.

Federico

**Comment by federicodotta** [comment]
Hi @yayip,

The script you run on the Frida CLI is different, because you start from a hook and call "this.a". If "a" is not a static function, "this" is an instance of your class and consequently in your Frida script will work, while in your Brida script will not because you call "class.function" instead of "instance.function".

Try to execute in the Frida CLI the "a" function as you do in the Brida script, directly from the "nf.a" class, because otherwise you are in a different scenario. 

You can try to paste directly in the Frida CLI something like that to see if it works correctly:

```JavaScript
Java.perform(function() {
        var aClass = Java.use("nf.a");
        var ret = aClass.a("AAAA","BBBB");
        console.log(ret);
    });
```

Federico

**Comment by yayip** [comment]
Hi @federicodotta, 

Yes you right, is there any other way to call this function ? 

![image](https://github.com/federicodotta/Brida/assets/39186995/88973227-3f85-4f24-a012-60309b6fd13a)

thanks,

**Comment by yayip** [comment]
Hi @federicodotta, 

Thanks to guide me, now I successfully run encrypt function with the script, but now I have problem to call decryption function because this function have two parameter (msg, key), key must be generated automatically by application, what best way to get key ?

`
encrypt: function(msg) {
        var ret = null;
        Java.perform(function() {
            Java.choose("nf.a", {
                onMatch: function(instance) {        
                    var resultB = instance.b(msg);
                    ret = resultB;
                },
                onComplete: function() {
                    //pass
                }
            });
        });
        return ret;
	},
`
![image](https://github.com/federicodotta/Brida/assets/39186995/8713e9e1-8c39-4096-a746-b0a2083e2058)

Thanks.

**Comment by federicodotta** [comment]
Hi @yayip,

You can do in many ways, but it depends on your application, on where the key is stored and on how often the key changes. 

You can for example add a hook to a function that uses or sets the key and save the key in a global JavaScript variable in your Brida script. Then you take the key from the variable in your Brida function. 

You can also also check the code of "nf.a" class. Maybe there is a get function that returns a key or the key is stored in a variable (with Frida you have access also to internal variables). Or maybe the key is stored in another object that you can get with Java.choose or with another hook.

Is the key never changes you can also simply add a hook to the "decrypt" function, retrieve the key and then copy the key directly in your Brida JS code. Simple but effective.

Hope this helps.

Federico
