### ISSUE TITLE
How to inspect all processes.

### ISSUE THREAD

**Issue by sieunhando** [federicodotta/Brida#14]
Hi, how I can inspect all processes in Android app? It'll be easy to find infomations. Thanks.

**Comment by federicodotta** [comment]
Hi sieunhando, if you try to inspect all processes in an Android app you will probably crash that application because you have too many hooks loaded.  

With Brida you can graphically inspect a single method or an entire class (adding hooks to all methods of that class).

Furthermore, Frida offers a tool named frida-trace that dinamically trace functions:
https://www.frida.re/docs/frida-trace/

Federico
