### ISSUE TITLE
Android analyze binary doesn't show binary hierarchy

### ISSUE THREAD

**Issue by deluser8** [federicodotta/Brida#28]
Hi~

I use Brida 3.0 and it can start server and spawn app correctly.

``` console
*** Brida Console ***  
Pyro server started correctly  
Application com.android.chrome spawned correctly  
Platform: Android  
```

However, in the "analyze binary" view, I can not see the binary hierarchy but only a single file named 'Binary'.

Thank you for your help.

**Comment by iLoveHairtail** [comment]
![image](https://user-images.githubusercontent.com/15990879/51968282-87a19800-24ac-11e9-8b71-76254b690eaa.png)

**Comment by deluser8** [comment]
Same with you @iLoveHairtail

**Comment by ta1bbty** [comment]
@deluser8 
Check this out #31

**Comment by federicodotta** [comment]
Hi! The issue is caused by the fact that you are not using Brida JS file, that defines getplatdorm, getallclasses and all the other methods used by Brida. You can download and use this file clicking on the "Load default JS file" button on the left of the "Frida JS file path" line. It is necessary to add your own methods to my JS file, because it contains Frida hooks used by Brida

**Comment by ta1bbty** [comment]
@federicodotta can you have a look at this #33 , am still struggling with it ( It's been a long time now :disappointed: ).

**Comment by federicodotta** [comment]
Hi ta1bbty! I just answered to your issue. I'm sorry for the delay.

Federico
