### ISSUE TITLE
Analyze Binary   EXCEption with load tree unable to find methd'get all classes'

### ISSUE THREAD

**Issue by rookiexjl** [federicodotta/Brida#52]
![1588212069](https://user-images.githubusercontent.com/19485623/80665578-7343b500-8acc-11ea-8631-514ad392bf81.jpg)

**Comment by rookiexjl** [comment]
![1588213418(1)](https://user-images.githubusercontent.com/19485623/80665672-b6058d00-8acc-11ea-8f15-7848218327cd.jpg)
other No problem

**Comment by federicodotta** [comment]
Hi, you must use and add to your method to Brida default JS files, because it contain many methods used by Brida, among which the getAllClasses(). You can copy default JS files with button "Load default JS file": it will copy one file for older Brida versions a 4 files for the newer version (that are then compiled with frida-compile). Refer to Brida documentation for details.

Federico
