### ISSUE TITLE
Brida Error with Spawn Application

### ISSUE THREAD

**Issue by C1inton** [federicodotta/Brida#66]
Hi,
I am facing an error: Please refer attached brida_console_log.txt file and attached screenshot.
how to resolve this issue?
[brida_console_log.txt](https://github.com/federicodotta/Brida/files/5432937/brida_console_log.txt)

![image](https://user-images.githubusercontent.com/30390369/97082740-8bcefb00-1629-11eb-8171-369e275481d9.png)

_Originally posted by @hacker7744 in https://github.com/federicodotta/Brida/issues/48#issuecomment-715914337_

**Comment by federicodotta** [comment]
I think you are using an old version of frida-compile, because your bug should be fixed in recent versions.

See: https://github.com/frida/frida-compile/pull/13

Try to update frida-compile

Federico

**Comment by hacker7744** [comment]
Thanks @federicodotta . Issue resolved after installing frida-compile@9.0.5. There are problem with newer versions.
Command to install: npm install frida-compile@9.0.5

**Comment by federicodotta** [comment]
Perfect! Yes, in the last version of frida-compile the "-x" option that i I use in Brida has been removed. I will in these days publish a release without the "-x" option. 

Thank you,
Federico

**Comment by federicodotta** [comment]
Hi @C1inton and @hacker7744 ,

the issue has been fixed in d5915fc701667e687c761a3ed605ad575abfc835.

Now Brida works with frida-compile 10 by default and by checking the new "Use old version of frida-compile" checkbox in the "Configurations" tab it is also possible to use Brida with frida-compile 9 and lower.

Please let me know if your issues are fixed.

Federico

**Comment by federicodotta** [comment]
No, unfortunately there is a compilation bug with frida-compile 10 that I'm trying to solve. At the moment the best option is to continue to use version 9.X.

Federico

**Comment by federicodotta** [comment]
Hi @C1inton @hacker7744 

The JS file pushed with commit 21ec48ff43bcdc621e40f3782b1298a76310fb58 can be used with frida-compile >= 10. 

It is not necessary to manually compile Brida. You can use the last release (Brida 0.5), using the following JS files from the Git repository instead of the ones packed with the release:

* res/androidDefaultHooks.js
* res/brida.js
* res/bridaFunctions.js
* res/iosDefaultHooks.js

Please let me know if you have any issue.

Federico
