### ISSUE TITLE
Can't Spawn app ( error: unknown option '-x')

### ISSUE THREAD

**Issue by oynomed** [federicodotta/Brida#72]
When I click Spawn application I encounter error: unknown option '-x', see screenshots
https://i.imgur.com/nvD4iC8.png

I'm using MemuPlay emulator.

**Comment by federicodotta** [comment]
Hi @oynomed,

in the the last Pre-Release version of Brida (v0.5pre, you can download it here: https://github.com/federicodotta/Brida/releases/tag/v0.5pre), there is a new flag named "Use old version of frida-compile". If you unflag that flag frida-compile is executed without the "-x" option.

Two things:
1) At the moment Brida does not work with frida-compile >= 10, so maybe you have to downgrade frida-compile to version 9.X
2) I noticed an error in your Brida configuration. In "Frida JS files folder" you have to select the **folder** of the Brida files, loaded with the button "Create default JS files". You can then add your own Frida hooks and functions to the "brida.js" file created by that button. Refer to [Brida Wiki](https://github.com/federicodotta/Brida/wiki/Start) for details.

Please let me know if your issue is solved.

Federico

**Comment by oynomed** [comment]
How to downgrade the frida-compile sir?
That file is already there when I install node.js.

**Comment by federicodotta** [comment]
With npm you can install a specific version of frida-compile with the following command:

npm install frida-compile@9

Federico

**Comment by oynomed** [comment]
got an error sir, see screenshots
https://i.imgur.com/X2NjQ7D.png

**Comment by federicodotta** [comment]
Hi @oynomed,

perfect, I close the issue.

Federico
