### ISSUE TITLE
Frida Hooks not executing.

### ISSUE THREAD

**Issue by oynomed** [federicodotta/Brida#74]
So I test the frida hook here
https://techblog.mediaservice.net/2020/11/android-okhttp3-4-2-certificate-pinning-bypass-for-frida-and-brida/
using the JS Editor, I copy and paste the code in brida.js, see screenshots here
https://i.imgur.com/N9L7Nbx.png
I save and reload js but nothing happens.
I test the code directly using FRIDA and its working fine.

May I know if I put the code correctly in brida.js file or I miss something?

**Comment by federicodotta** [comment]
Hi!

Brida code is compiled using frida-compile. When you edit the JS you have to use "Compile&spawn", "Compile&attach" or "Compile&reload" in order to recompile and load the updated brida.js file. "Compile", "Attach" and "Reload" should be used only when you don't updated the brida.js file in order to speed-up those operations when compile is not necessary.

If you are using last version of Brida, you can load that pinning bypass script also without editing brida.js file from the graphical interface of Brida in the "Hooks and functions" -> "Android" section.  That script is included in both "SSL pinning bypass with CA certificate" (that requries that you put your CA public certificate in /data/local/tmp/cert-der.crt") and in "SSL pinning bypass without CA".

Federico

**Comment by oynomed** [comment]
Thanks sir, I will try
