### ISSUE TITLE
Unable to run frida-compile

### ISSUE THREAD

**Issue by krviolent** [federicodotta/Brida#76]
I run burp suite 2021.4 with "sudo".
Pyro server starts properly, but I get 'permission denied' error while staring frida-compile
*** Brida Console *** 
 Pyro server started correctly 
 Exception during frida-compile java.io.IOException: Cannot run program "/usr/local/bin/node_modules/frida-compile/bin/": error=13, Permission denied 
java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) java.base/java.lang.Runtime.exec(Runtime.java:592)

**Comment by federicodotta** [comment]
Hi @krviolent,

it is not necessary to run burp with sudo. Brida  should work also executed by a unprivileged user.

In the frida-compile path you have to set the full path of frida-compile **including** the binary, and not only the folder. 

Please note that at the moment you should use frida-compile < 10, because version 10 has issues that I'm trying to solve.

Federico

**Comment by federicodotta** [comment]
Hi @krviolent , I close the issue, if you have other doubts please open a new issue.

Federico
