### ISSUE TITLE
求解决

### ISSUE THREAD

**Issue by shuai19980** [federicodotta/Brida#83]
![image](https://user-images.githubusercontent.com/62590857/126920759-e39f3fb1-f4a8-4f68-88f8-0fa28c7ade64.png)

**Comment by federicodotta** [comment]
Hi @shuai19980 

from the error it seems that you have an error in one NodeJS modules. Probably you have to fix this error before being able to use Frida-Compile

Federico

**Comment by federicodotta** [comment]
Hi @shuai19980 

I investigated better your issue and it is caused by a bug in Brida compilation in presence of nodeJs warnings.

I fixed the issue and released a new Brida pre-release. You can found the fixed version here:

https://github.com/federicodotta/Brida/releases/tag/0.5pre2

Please let me know if your issue is solved.

Federico

**Comment by ppuuoo** [comment]
降低node版本14完美解决

**Comment by shuai19980** [comment]
弄好了，非常感谢
