### ISSUE TITLE
Spawn application not working

### ISSUE THREAD

**Issue by Banginpadr** [federicodotta/Brida#85]
internal/modules/cjs/loader.js:892  

throw err;  

^    

Error: Cannot find module '/opt/burp/brida/brida.js'  

Require stack:  - /Users/banginpadr/node_modules/frida-compile/bin/compile.js  

at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)  
at Function.resolve (internal/modules/cjs/helpers.js:98:19)  
at Object.  (/Users/c0d3x27/node_modules/frida-compile/bin/compile.js:28:27)  
at Module._compile (internal/modules/cjs/loader.js:1072:14)  
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)  
at Module.load (internal/modules/cjs/loader.js:937:32)  
at Function.Module._load (internal/modules/cjs/loader.js:778:12)  
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) 
 at internal/main/run_main_module.js:17:47 {  code: 'MODULE_NOT_FOUND',  requireStack: [ '/Users/banginpadr/node_modules/frida-compile/bin/compile.js' ]  }  Error during frida-compile. Aborting. 

First of all thank you very much for this work. It takes time and effort to make something like this. this being said, I hate to make issues but after reading and searching for 4 days I have to. I'm getting this error and I don't know how to fix it. I cant only start the server but is not letting me do anything also, like spawn an application or attach an application.

for some reason I don't have `'/opt/burp/brida/brida.js'`

mac OS 10.13
pyvenv python 3.6.5
venvertuarlenv

**Comment by federicodotta** [comment]
Hi @Banginpadr,

Thank you! No problem for the issue!

In order to make Brida work you have to use Brida default files, because Brida core requires some Frida scripts to work. If you click on button "Load default JS files" you can copy Brida Js default files in a directory of your choice (and the path in inserted in the "Frida JS files folder" field). Then you can spawn or attach to an application. You can then add your own exports and Frida hooks in the Brida.js file in that folder. You can find additional details in the Wiki here: https://github.com/federicodotta/Brida/wiki/Start

Please let me know if this solves your issue.

Federico.

**Comment by Banginpadr** [comment]
Thank you very much bro, yes it worked for me. I'm closing this now. sei un grande fra..
